name: Deploy

on:
  push:
    branches: [ "main", "initial" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: Build & Deploy
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: actions/github-script@v6
        with:
          script: |
            let data = fs.readFileSync('index.html', 'utf-8')
            data = data.replace(new RegEx('<!--TEST_MAPS-->.*<!--/TEST_MAPS-->'), '<!--And it\'s gone!-->')
            fs.writeFileSync('index.html', data, 'utf-8')
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

